### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by pinpox** [farcaller/gonix#1]
> These bindings depend on the unstable nix C API, that's not currently merged upstream. 

It looks like https://github.com/NixOS/nix/pull/8699 was merged. Does that mean gonix can be used with current nix versions? Is it considered stable and still maintained?

**Comment by farcaller** [comment]
I haven't built it against the version that was merged in yet, hopefully, I'll have time to do that in the coming week.

**Comment by pinpox** [comment]
Cool, thanks for the update! Feel free to give me a ping when there is something to test

**Comment by farcaller** [comment]
This is pretty much blocked on https://github.com/farcaller/gonix/pull/2. I'll close this bug and you can track the progress in there instead.
